CodeSoom/project-react-2-onys-programmer

index.html

Remove "/" of "/main.js" in index.html

Try to release this app

---

src/GuideMessage.jsx
src/GuideMessage.test.jsx
src/HabitForm.jsx

detach GuideMessage from habitForm

Detach GuideMessage

---

src/index.jsx

add a basename of BrowserRouter : project-react-2-onys-programmer

Add a basename

---

src/index.jsx

Correct basename

---

src/ExerciseExample.jsx
src/ExerciseExample.test.jsx
src/HabitMatrix.jsx
src/HorizontalFlexibility.jsx
src/HorizontalFlexibility.test.jsx

It contains 3 category inputs and a button

Implement HorizontalFlexiblility

---

src/CategoryCreateContainer.jsx
src/CategoryCreateContainer.test.jsx
src/CategoryForm.jsx
src/actions.js
src/reducer.js
src/reducer.test.js

Make "입력" button work: it sets categories

Implement "입력" button

---

index.html
src/App.test.jsx
src/CategoryCreateContainer.jsx
src/CategoryCreateContainer.test.jsx
src/CategoryForm.jsx
src/CategoryForm.test.jsx
src/HabitMatrix.jsx
src/HabitMatrixContainer.jsx
src/HabitMatrixContainer.test.jsx
src/actions.js
src/reducer.js
src/reducer.test.js

It saves 3 categories of habit to state

Implement Category Form

---

src/HabitMatrixContainer.jsx
src/HorizontalFlexibility.jsx
src/HorizontalFlexibility.test.jsx

From HabitMatrixContainer to HorizontalFlexibility

Immigrate CategoryCreateContainer

---

src/App.jsx
src/App.test.jsx
src/HabitForm.jsx

Link HabitForm to HorizontalFlexibility when 입력 button is clicked

Link HabitForm to HorizontalFlexibility

---

src/App.jsx
src/App.test.jsx
src/CategoryCreateContainer.test.jsx
src/CategoryForm.jsx
src/CategoryForm.test.jsx
src/HorizontalFlexibility.test.jsx

Apply VerticalFlexibility router: when 입력 button in HorizontalFlexibility is clicked, go to VerticalFlexibility

Apply VerticalFlexibility router

---

src/App.jsx
src/CategoryCreateContainer.test.jsx
src/HabitMatrixContainer.test.jsx
src/VerticalFlexibility.jsx
src/VerticalFlexibilityContainer.jsx
src/VerticalFlexibilityContainer.test.jsx

Show 3 categories of the habit on VerticalFlexibilityPage

Show 3 categories

---

__mocks__/fileMock.js
__mocks__/styleMock.js
index.html
jest.config.js
package-lock.json
package.json
src/HomePage.jsx
src/assets/images.js

Plus try to fix import/export problem

    Try to fix jest problem

---

src/HomePage.jsx

Make components to be center

---

index.html
src/index.jsx

Plus add a basename in index.jsx

Undo resetting src path

---

index.html
src/index.jsx

Plus remove a basename of the browserrouter

Make src path to be /main.js

---

src/CategoryForm.jsx
src/GlobalExample.jsx

Make components to be right location
plus set margin

Apply css in CategoryForm

---

jest.config.js
src/VerticalFlexibility.jsx

Show username at the header

---

src/CategoryForm.jsx
src/GlobalExample.jsx
src/GreetPage.jsx
src/HabitForm.jsx
src/HomePage.jsx
src/VerticalFlexibility.jsx

Unify html tags of emotion

---

src/Experience.jsx
src/Experience.test.jsx
src/VerticalFlexibility.jsx
src/VerticalFlexibility.test.jsx
src/actions.js
src/reducer.js
src/reducer.test.js

Todo: refactoring by set a reducer

Implement a progress bar named experience bar

---

src/VerticalFlexibility.jsx
src/reducer.js
src/reducer.test.js

Plus change all string values of status to number values

Fix undefined error of setStatus test case

---

src/reducer.js

Fix NaN problem with addExperience reducer

---

src/App.test.jsx
src/Experience.jsx
src/Experience.test.jsx
src/ExperienceContainer.jsx
src/ExperienceContainer.test.jsx
src/VerticalFlexibility.jsx
src/VerticalFlexibility.test.jsx
src/VerticalFlexibilityContainer.jsx
src/VerticalFlexibilityContainer.test.jsx
src/actions.js
src/reducer.js
src/reducer.test.js

Plus Implement onClick function that executes addExperience
Plus Fix undefined error of App.test

Implement the progress bar that uses state.status

---

src/App.jsx
src/App.test.jsx
src/CategoryForm.jsx
src/GainProficiency.jsx
src/GainProficiency.test.jsx
src/GainProficiencyContainer.jsx
src/GainProficiencyContainer.test.jsx

Rename VerticalFlexibility to GainProficiency

---

src/Experience.jsx

LV depends on experience value

Change LV logic

---

src/Experience.jsx

By Changing experienceBar logic

Make experienceBar be initialized when LV up

---

src/GreetPage.jsx
src/GreetPage.test.jsx

It shows the meaning of process better

Rename button 습관생성 to 튜토리얼 시작

---

src/GreetPage.jsx
src/GreetPage.test.jsx

It introduces this project better

Change Intro of GreetPage

---

src/GuideMessage.jsx

It does not fit for the first guide message

Change a guide message

---

src/Experience.jsx

Declare const level, experienceOfLevel and maxValueOfExperienceBar
for reusing

Clarify value of each property of progress

---

src/GainProficiencyContainer.test.jsx
src/actions.js

Plus make an action for showModal reducer

Add a showModal reducer test in GainProficiencyContainer.test

---

src/GuideMessage.jsx

Add an icon

---

src/CategoryForm.jsx

Change a Container message

---

src/CategoryForm.jsx
src/GlobalExample.jsx

Make the most important component to be seen first

Rearrange components

---

src/CategoryForm.jsx

Add a habit image

---

src/CategoryForm.jsx
src/Habit.jsx
src/Habit.test.jsx

ToDo: Show name of the habit in Habit component

Separate Habit from CategoryForm

---

src/GreetPage.jsx
src/GreetPage.test.jsx

Rearrange components in GreetPage

---

src/GainProficiency.jsx

Add a skillBook image at gain-proficiency page

---

src/CategoryCreateContainer.test.jsx
src/CategoryForm.jsx
src/GainProficiency.jsx
src/GainProficiency.test.jsx
src/Habit.jsx
src/Habit.test.jsx
src/HabitContainer.jsx
src/HabitContainer.test.jsx

in Habit component by using useSelector
Todo: fix test errors

Refactor showing the name of objectHabit
